/* OpenFF parameterized systems + OpenMM 8.2 Reference WebAssembly.
 * Small molecules are typed with Sage in-browser; prepared protein fixtures
 * carry an exact numeric Rosemary System generated by the official OpenFF stack. */

self.importScripts('./rdkit/dist/RDKit_minimal.js');

const KJ_TO_KCAL = 1 / 4.184;
let openmmPromise;
let rdkitPromise;
let parameterizerPromise;
let implicitSolventPromise;
let simulationOptionsPromise;
let conformerProtocolPromise;

function progress(id, phase, model, calculation) {
  self.postMessage({ type: 'progress', id, phase, model, calculation });
}

function getRDKit(id) {
  if (!rdkitPromise) {
    progress(id, 'Loading RDKit chemical perception…', 0.08, 0);
    rdkitPromise = self.initRDKitModule({
      locateFile: (file) => new URL(`./rdkit/dist/${file}`, self.location.href).href,
    }).catch((error) => {
      rdkitPromise = null;
      throw error;
    });
  }
  return rdkitPromise;
}

function getOpenMM(id) {
  if (!openmmPromise) {
    progress(id, 'Loading OpenMM WebAssembly…', 0.16, 0);
    openmmPromise = import('./openmm/molarium-openmm.js')
      .then((module) => module.default({
        locateFile: (file) => new URL(`./openmm/${file}`, self.location.href).href,
      }))
      .catch((error) => {
        openmmPromise = null;
        throw error;
      });
  }
  return openmmPromise;
}

function getParameterizer() {
  parameterizerPromise ??= import('./openff/sage-parameterizer.js').catch((error) => {
    parameterizerPromise = null;
    throw error;
  });
  return parameterizerPromise;
}

function getImplicitSolvent() {
  implicitSolventPromise ??= import('./openff/implicit-solvent.js').catch((error) => {
    implicitSolventPromise = null;
    throw error;
  });
  return implicitSolventPromise;
}

function getSimulationOptions() {
  simulationOptionsPromise ??= import('./openff/simulation-options.js').catch((error) => {
    simulationOptionsPromise = null;
    throw error;
  });
  return simulationOptionsPromise;
}

function getConformerProtocol() {
  conformerProtocolPromise ??= import('./openff/conformer-protocol.js').catch((error) => {
    conformerProtocolPromise = null;
    throw error;
  });
  return conformerProtocolPromise;
}

async function parameterizeMolecule(id, molecule) {
  if (molecule.parameterization?.system) {
    progress(id, `Loading ${molecule.parameterization.forcefield} parameters…`, 0.9, 0.03);
    return molecule.parameterization;
  }
  const [rdkit, { parameterizeSage }] = await Promise.all([getRDKit(id), getParameterizer()]);
  progress(id, 'Assigning OpenFF Sage 2.1 parameters…', 0.45, 0.03);
  return parameterizeSage(rdkit, molecule);
}

function lastError(module) {
  return module.UTF8ToString(module._molarium_last_error()) || 'OpenMM calculation failed';
}

function requireSuccess(module, success) {
  if (!success) throw new Error(lastError(module));
}

function allocate(module, array, heapName, shift) {
  if (!array.byteLength) return 0;
  const pointer = module._malloc(array.byteLength);
  module[heapName].set(array, pointer >> shift);
  return pointer;
}

function integerField(terms, field) { return Int32Array.from(terms, (term) => term[field]); }
function numberField(terms, field) { return Float64Array.from(terms, (term) => term[field]); }

function initializeSmirnoffSystem(module, molecule, system, implicitSolvent = null,
                                  timestepPs = 0.001, cutoffNm = 0,
                                  positionsAngstrom = null) {
  const constraints = system.constraints;
  const bonds = system.bonds;
  const angles = system.angles;
  const torsions = system.torsions;
  const exceptions = system.exceptions;
  const arrays = [
    numberField(system.particles, 'mass_amu'),
    positionsAngstrom ? Float64Array.from(positionsAngstrom)
      : Float64Array.from(molecule.atoms.flatMap((atom) => [atom.x, atom.y, atom.z])),
    integerField(constraints, 'i'), integerField(constraints, 'j'), numberField(constraints, 'distance_nm'),
    integerField(bonds, 'i'), integerField(bonds, 'j'), numberField(bonds, 'r0_nm'), numberField(bonds, 'k_kj_nm2'),
    integerField(angles, 'i'), integerField(angles, 'j'), integerField(angles, 'k'),
    numberField(angles, 'theta0_rad'), numberField(angles, 'k_kj_rad2'),
    integerField(torsions, 'i'), integerField(torsions, 'j'), integerField(torsions, 'k'), integerField(torsions, 'l'),
    integerField(torsions, 'periodicity'), numberField(torsions, 'phase_rad'), numberField(torsions, 'k_kj'),
    numberField(system.nonbonded, 'charge_e'), numberField(system.nonbonded, 'sigma_nm'), numberField(system.nonbonded, 'epsilon_kj'),
    integerField(exceptions, 'i'), integerField(exceptions, 'j'), numberField(exceptions, 'chargeprod_e2'),
    numberField(exceptions, 'sigma_nm'), numberField(exceptions, 'epsilon_kj'),
    implicitSolvent ? numberField(implicitSolvent.particles, 'radius_nm') : new Float64Array(),
    implicitSolvent ? numberField(implicitSolvent.particles, 'scale') : new Float64Array(),
  ];
  const pointers = [];
  try {
    for (const array of arrays) {
      pointers.push(allocate(module, array, array instanceof Int32Array ? 'HEAP32' : 'HEAPF64',
        array instanceof Int32Array ? 2 : 3));
    }
    requireSuccess(module, module._molarium_initialize_sage(
      molecule.atoms.length, pointers[0], pointers[1],
      constraints.length, pointers[2], pointers[3], pointers[4],
      bonds.length, pointers[5], pointers[6], pointers[7], pointers[8],
      angles.length, pointers[9], pointers[10], pointers[11], pointers[12], pointers[13],
      torsions.length, pointers[14], pointers[15], pointers[16], pointers[17], pointers[18], pointers[19], pointers[20],
      pointers[21], pointers[22], pointers[23],
      exceptions.length, pointers[24], pointers[25], pointers[26], pointers[27], pointers[28],
      implicitSolvent ? 1 : 0, pointers[29], pointers[30],
      timestepPs, cutoffNm,
    ));
  } finally {
    pointers.forEach((pointer) => { if (pointer) module._free(pointer); });
  }
}

function setPositions(module, positionsAngstrom) {
  const positions = Float64Array.from(positionsAngstrom);
  const pointer = allocate(module, positions, 'HEAPF64', 3);
  try {
    requireSuccess(module, module._molarium_set_positions(pointer, positions.length));
  } finally {
    module._free(pointer);
  }
}

function readPositions(module, atomCount) {
  const length = atomCount * 3;
  const pointer = module._malloc(length * Float64Array.BYTES_PER_ELEMENT);
  try {
    requireSuccess(module, module._molarium_get_positions(pointer, length));
    return module.HEAPF64.slice(pointer >> 3, (pointer >> 3) + length);
  } finally {
    module._free(pointer);
  }
}

function readForces(module, atomCount) {
  const length = atomCount * 3;
  const pointer = module._malloc(length * Float64Array.BYTES_PER_ELEMENT);
  try {
    requireSuccess(module, module._molarium_get_forces(pointer, length));
    return module.HEAPF64.slice(pointer >> 3, (pointer >> 3) + length);
  } finally {
    module._free(pointer);
  }
}

function captureFrame(module, atomCount, step) {
  const energyKj = module._molarium_get_potential_energy();
  if (!Number.isFinite(energyKj)) throw new Error(lastError(module));
  return { step, energy: energyKj * KJ_TO_KCAL, positions: readPositions(module, atomCount) };
}

function packFrames(frames, atomCount) {
  const stride = atomCount * 3;
  const frameEnergies = Float64Array.from(frames, (frame) => frame.energy);
  const frameSteps = Int32Array.from(frames, (frame) => frame.step);
  const trajectory = new Float64Array(frames.length * stride);
  frames.forEach((frame, index) => trajectory.set(frame.positions, index * stride));
  return { frameEnergies, frameSteps, trajectory };
}

function maximumConstraintError(positionsAngstrom, constraints) {
  let maximum = 0;
  for (const term of constraints) {
    const first = term.i * 3, second = term.j * 3;
    const distanceAngstrom = Math.hypot(
      positionsAngstrom[first] - positionsAngstrom[second],
      positionsAngstrom[first + 1] - positionsAngstrom[second + 1],
      positionsAngstrom[first + 2] - positionsAngstrom[second + 2],
    );
    maximum = Math.max(maximum,
      Math.abs(distanceAngstrom * 0.1 - term.distance_nm) / term.distance_nm);
  }
  return constraints.length ? maximum : null;
}

async function runCalculation(message) {
  const { id, job, molecule, options = {} } = message;
  const started = performance.now();
  const parameterized = await parameterizeMolecule(id, molecule);
  const [{ obc2Parameters, requestedImplicitSolvent }, { configureSimulationSystem }] = await Promise.all([
    getImplicitSolvent(), getSimulationOptions(),
  ]);
  const implicitModel = requestedImplicitSolvent(options);
  const implicitSolvent = implicitModel === 'obc2'
    ? obc2Parameters(molecule, parameterized.system) : null;
  const counts = Object.fromEntries(Object.entries(parameterized.system).map(([name, terms]) => [name, terms.length]));
  if (job === 'parameters') {
    self.postMessage({
      type: 'result', id, job,
      forcefield: parameterized.forcefield,
      chargeModel: parameterized.chargeModel,
      sourceSha256: parameterized.sourceSha256,
      system: parameterized.system,
      labels: parameterized.labels,
      parameterCounts: counts,
      elapsedMs: performance.now() - started,
    });
    return;
  }

  const simulationConfig = configureSimulationSystem(molecule, parameterized.system, options);
  const configuredSystem = simulationConfig.system;

  const module = await getOpenMM(id);
  progress(id, `Creating OpenMM System · ${counts.particles} atoms · ${counts.torsions} torsions · ${counts.exceptions} exceptions…`, 0.9, 0.08);
  const conformerStride = molecule.atoms.length * 3;
  const initialConformers = job === 'conformers' ? options.initialConformers : null;
  const fixedConformers = job === 'fixed-conformers' ? options.initialConformers : null;
  const scoreCoordinates = job === 'conformer-score' ? options.coordinateStack : null;
  if (job === 'conformers' && (!ArrayBuffer.isView(initialConformers)
      || !initialConformers.length || initialConformers.length % conformerStride))
    throw new Error('OpenMM conformer benchmark received an invalid ETKDG coordinate stack');
  if (job === 'conformer-score' && (!ArrayBuffer.isView(scoreCoordinates)
      || !scoreCoordinates.length || scoreCoordinates.length % conformerStride
      || scoreCoordinates.length / conformerStride > 4096))
    throw new Error('OpenMM conformer judge received an invalid coordinate stack');
  if (job === 'fixed-conformers' && (!ArrayBuffer.isView(fixedConformers)
      || !fixedConformers.length || fixedConformers.length % conformerStride
      || fixedConformers.length / conformerStride > 64))
    throw new Error('OpenMM fixed-scaffold relaxation received an invalid coordinate stack');
  const initialPositions = job === 'conformers'
    ? initialConformers.subarray(0, conformerStride)
    : job === 'conformer-score' ? scoreCoordinates.subarray(0, conformerStride)
      : job === 'fixed-conformers' ? fixedConformers.subarray(0, conformerStride) : null;
  initializeSmirnoffSystem(module, molecule, configuredSystem, implicitSolvent,
    simulationConfig.timestepPs, simulationConfig.cutoffNm, initialPositions);
  progress(id, `${parameterized.forcefield} System ready`, 1, 0.14);

  if (job === 'fixed-conformers') {
    const fixedAtomIndices = Array.from(options.fixedAtomIndices || [], Number);
    if (fixedAtomIndices.some((index) => !Number.isInteger(index)
        || index < 0 || index >= molecule.atoms.length)
        || new Set(fixedAtomIndices).size !== fixedAtomIndices.length)
      throw new Error('Fixed scaffold indices must be unique valid atom indices');
    const conformerCount = fixedConformers.length / conformerStride;
    const iterations = Math.max(0, Math.min(250,
      Math.round(Number(options.fixedRelaxIterations ?? 60))));
    const stepScale = Math.max(1e-8, Math.min(1e-2,
      Number(options.fixedRelaxStepScale ?? 1e-4)));
    const maximumDisplacementAngstrom = Math.max(1e-5, Math.min(0.1,
      Number(options.fixedRelaxMaximumDisplacementAngstrom ?? 0.01)));
    const relaxedConformers = new Float64Array(fixedConformers.length);
    const initialEnergies = new Float64Array(conformerCount);
    const finalEnergies = new Float64Array(conformerCount);
    const fixedSet = new Set(fixedAtomIndices);
    for (let conformer = 0; conformer < conformerCount; conformer++) {
      const target = fixedConformers.subarray(conformer * conformerStride,
        (conformer + 1) * conformerStride);
      setPositions(module, target);
      const initialEnergyKj = module._molarium_get_potential_energy();
      if (!Number.isFinite(initialEnergyKj)) throw new Error(lastError(module));
      initialEnergies[conformer] = initialEnergyKj * KJ_TO_KCAL;
      for (let iteration = 0; iteration < iterations; iteration++) {
        requireSuccess(module, module._molarium_relax_fixed(1, stepScale,
          maximumDisplacementAngstrom));
        if (fixedAtomIndices.length) {
          const positions = readPositions(module, molecule.atoms.length);
          for (const atom of fixedAtomIndices) for (let axis = 0; axis < 3; axis++)
            positions[atom * 3 + axis] = target[atom * 3 + axis];
          setPositions(module, positions);
        }
      }
      const positions = readPositions(module, molecule.atoms.length);
      // Preserve the reference coordinates bit-for-bit at the worker boundary.
      for (const atom of fixedAtomIndices) for (let axis = 0; axis < 3; axis++)
        positions[atom * 3 + axis] = target[atom * 3 + axis];
      setPositions(module, positions);
      const finalEnergyKj = module._molarium_get_potential_energy();
      if (!Number.isFinite(finalEnergyKj)) throw new Error(lastError(module));
      finalEnergies[conformer] = finalEnergyKj * KJ_TO_KCAL;
      relaxedConformers.set(positions, conformer * conformerStride);
      progress(id, `Relaxing edited pose ${conformer + 1}/${conformerCount}…`, 1,
        0.16 + 0.78 * (conformer + 1) / conformerCount);
    }
    const openmmVersion = module.UTF8ToString(module._molarium_openmm_version());
    module._molarium_destroy();
    self.postMessage({
      type:'result', id, job, conformers:relaxedConformers,
      initialEnergies, finalEnergies, conformerCount, iterations,
      fixedAtomCount:fixedAtomIndices.length,
      movableAtomCount:molecule.atoms.length - fixedSet.size,
      elapsedMs:performance.now() - started,
      openmmVersion,
      forcefield:parameterized.forcefield, chargeModel:parameterized.chargeModel,
      sourceSha256:parameterized.sourceSha256, platform:'Reference',
      backend:'OpenMM WebAssembly fixed-scaffold Sage relaxation', unit:'kcal/mol',
    }, [relaxedConformers.buffer, initialEnergies.buffer, finalEnergies.buffer]);
    return;
  }

  if (job === 'conformer-score') {
    const coordinateCount = scoreCoordinates.length / conformerStride;
    const energies = new Float64Array(coordinateCount);
    const scoreStarted = performance.now();
    for (let index = 0; index < coordinateCount; index++) {
      setPositions(module,
        scoreCoordinates.subarray(index * conformerStride, (index + 1) * conformerStride));
      const energyKj = module._molarium_get_potential_energy();
      if (!Number.isFinite(energyKj)) throw new Error(lastError(module));
      energies[index] = energyKj * KJ_TO_KCAL;
      if (index === coordinateCount - 1 || index % Math.max(1, Math.floor(coordinateCount / 40)) === 0)
        progress(id, `Common Sage judge · geometry ${index + 1}/${coordinateCount}…`, 1,
          0.16 + 0.78 * (index + 1) / coordinateCount);
    }
    const positions = Float64Array.from(
      scoreCoordinates.subarray(0, conformerStride));
    const result = {
      type: 'result', id, job, positions, energies, coordinateCount,
      elapsedMs: performance.now() - started,
      scoreMs: performance.now() - scoreStarted,
      openmmVersion: module.UTF8ToString(module._molarium_openmm_version()),
      forcefield: parameterized.forcefield, chargeModel: parameterized.chargeModel,
      sourceSha256: parameterized.sourceSha256,
      platform: 'Reference', backend: 'OpenMM WebAssembly conformer judge',
      unit: 'kcal/mol', implicitSolvent: implicitSolvent?.model || null,
      constraintMode: simulationConfig.constraintMode,
      constraintCount: simulationConfig.constraints.length,
    };
    module._molarium_destroy();
    self.postMessage(result, [positions.buffer, energies.buffer]);
    return;
  }

  if (job === 'conformers') {
    const { conformerSearchProtocol } = await getConformerProtocol();
    const protocol = conformerSearchProtocol(options);
    const replicaCount = initialConformers.length / conformerStride;
    const frameCount = protocol.stages.length;
    const frameSteps = new Int32Array(frameCount);
    let cumulative = 0;
    protocol.stages.forEach((stage, frame) => {
      cumulative += stage.steps;
      frameSteps[frame] = cumulative;
    });
    const ensembleEnergies = new Float64Array(frameCount * replicaCount);
    const ensembleTrajectory = new Float64Array(frameCount * replicaCount * conformerStride);
    const stageElapsedMs = new Float64Array(frameCount);
    const setupMs = performance.now() - started;
    const searchStarted = performance.now();
    let maximumFinalConstraintError = 0;
    const capture = (frame, replica) => {
      const captureStarted = performance.now();
      const energyKj = module._molarium_get_potential_energy();
      if (!Number.isFinite(energyKj)) throw new Error(lastError(module));
      const positions = readPositions(module, molecule.atoms.length);
      ensembleEnergies[frame * replicaCount + replica] = energyKj * KJ_TO_KCAL;
      ensembleTrajectory.set(positions,
        (frame * replicaCount + replica) * conformerStride);
      stageElapsedMs[frame] += performance.now() - captureStarted;
      return positions;
    };
    for (let replica = 0; replica < replicaCount; replica++) {
      setPositions(module,
        initialConformers.subarray(replica * conformerStride, (replica + 1) * conformerStride));
      capture(0, replica);
      for (let frame = 1; frame < frameCount; frame++) {
        const stage = protocol.stages[frame];
        const stageStarted = performance.now();
        if (stage.kind === 'relax') {
          requireSuccess(module, module._molarium_relax_fixed(stage.steps, 1e-4, 0.01));
        } else {
          requireSuccess(module, module._molarium_set_dynamics(stage.temperature, stage.collisionRate));
          requireSuccess(module, module._molarium_step(stage.steps, stage.temperature));
        }
        stageElapsedMs[frame] += performance.now() - stageStarted;
        const positions = capture(frame, replica);
        if (frame === frameCount - 1 && simulationConfig.constraints.length)
          maximumFinalConstraintError = Math.max(maximumFinalConstraintError,
            maximumConstraintError(positions, simulationConfig.constraints));
      }
      if (replica === replicaCount - 1 || replica % Math.max(1, Math.floor(replicaCount / 40)) === 0)
        progress(id, `OpenMM serial conformer ${replica + 1}/${replicaCount}…`, 1,
          0.16 + 0.78 * (replica + 1) / replicaCount);
    }
    const searchMs = performance.now() - searchStarted;
    const lastFrame = frameCount - 1;
    let bestReplica = 0;
    for (let replica = 1; replica < replicaCount; replica++)
      if (ensembleEnergies[lastFrame * replicaCount + replica]
          < ensembleEnergies[lastFrame * replicaCount + bestReplica]) bestReplica = replica;
    const positions = ensembleTrajectory.slice(
      (lastFrame * replicaCount + bestReplica) * conformerStride,
      (lastFrame * replicaCount + bestReplica + 1) * conformerStride,
    );
    const result = {
      type: 'result', id, job, positions,
      initialEnergy: ensembleEnergies[bestReplica],
      finalEnergy: ensembleEnergies[lastFrame * replicaCount + bestReplica],
      elapsedMs: performance.now() - started, setupMs, searchMs,
      stageElapsedMs, bestReplica,
      openmmVersion: module.UTF8ToString(module._molarium_openmm_version()),
      forcefield: parameterized.forcefield, chargeModel: parameterized.chargeModel,
      sourceSha256: parameterized.sourceSha256,
      platform: 'Reference', backend: 'OpenMM WebAssembly serial conformers',
      unit: 'kcal/mol', timestepFs: simulationConfig.timestepPs * 1000,
      frameCount, frameSteps, replicaCount, ensembleEnergies, ensembleTrajectory,
      ensembleLayout: 'frame-replica-xyz', homogeneous: true,
      implicitSolvent: implicitSolvent?.model || null,
      constraintMode: simulationConfig.constraintMode,
      constraintCount: simulationConfig.constraints.length,
      derivedConstraintCount: simulationConfig.derivedConstraintCount,
      cutoffNm: simulationConfig.cutoffNm || null,
      constraintError: simulationConfig.constraints.length ? maximumFinalConstraintError : null,
      conformerSearchSteps: protocol.searchSteps,
      conformerMinimizationIterations: protocol.minimizationIterations,
      conformerStageLabels: protocol.stages.map((stage) => stage.label),
    };
    module._molarium_destroy();
    self.postMessage(result, [
      positions.buffer, frameSteps.buffer, ensembleEnergies.buffer,
      ensembleTrajectory.buffer, stageElapsedMs.buffer,
    ]);
    return;
  }

  const frames = [captureFrame(module, molecule.atoms.length, 0)];
  const initialEnergy = frames[0].energy;
  if (job === 'geometry') {
    const tolerance = Number(options.tolerance ?? 5);
    const maxIterations = Math.max(0, Number(options.maxIterations ?? 750));
    const chunks = Math.min(8, Math.max(1, Math.ceil(maxIterations / 25)));
    let completed = 0;
    for (let index = 0; index < chunks && completed < maxIterations; index++) {
      const iterations = index === chunks - 1
        ? maxIterations - completed
        : Math.min(25, maxIterations - completed);
      requireSuccess(module, module._molarium_minimize(tolerance, iterations));
      completed += iterations;
      frames.push(captureFrame(module, molecule.atoms.length, completed));
      progress(id, 'Minimizing with OpenMM Reference…', 1, 0.16 + 0.76 * completed / Math.max(1, maxIterations));
    }
  } else if (job === 'dynamics') {
    const steps = Math.max(0, Number(options.steps ?? 250));
    const temperature = Number(options.temperature ?? 300);
    const savedFrameCount = Math.max(2, Math.min(steps + 1, Math.round(Number(options.savedFrameCount ?? 26))));
    let completed = 0;
    for (let frame = 1; frame < savedFrameCount; frame++) {
      const targetStep = Math.round(frame * steps / (savedFrameCount - 1));
      const chunk = targetStep - completed;
      requireSuccess(module, module._molarium_step(chunk, temperature));
      completed = targetStep;
      frames.push(captureFrame(module, molecule.atoms.length, completed));
      progress(id, 'Running OpenMM Langevin dynamics…', 1, 0.16 + 0.76 * completed / Math.max(1, steps));
    }
  } else if (job !== 'energy') {
    throw new Error(`Unknown OpenMM job type: ${job}`);
  }

  progress(id, 'Collecting OpenMM results…', 1, 0.94);
  const finalFrame = frames.at(-1);
  const { frameEnergies, frameSteps, trajectory } = packFrames(frames, molecule.atoms.length);
  const positions = finalFrame.positions;
  const forces = readForces(module, molecule.atoms.length);
  const result = {
    type: 'result', id, job,
    initialEnergy,
    finalEnergy: finalFrame.energy,
    positions,
    forces,
    elapsedMs: performance.now() - started,
    openmmVersion: module.UTF8ToString(module._molarium_openmm_version()),
    forcefield: parameterized.forcefield,
    chargeModel: parameterized.chargeModel,
    sourceSha256: parameterized.sourceSha256,
    platform: 'Reference',
    backend: 'OpenMM WebAssembly',
    unit: 'kcal/mol',
    timestepFs: job === 'dynamics' ? simulationConfig.timestepPs * 1000 : null,
    frameCount: frames.length,
    frameEnergies,
    frameSteps,
    trajectory,
    parameterCounts: counts,
    implicitSolvent: implicitSolvent?.model || null,
    constraintMode: simulationConfig.constraintMode,
    constraintCount: simulationConfig.constraints.length,
    derivedConstraintCount: simulationConfig.derivedConstraintCount,
    cutoffNm: simulationConfig.cutoffNm || null,
    constraintError: job === 'energy' ? null
      : maximumConstraintError(positions, simulationConfig.constraints),
  };
  module._molarium_destroy();
  self.postMessage(result, [positions.buffer, forces.buffer, frameEnergies.buffer, frameSteps.buffer, trajectory.buffer]);
}

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'run') return;
  runCalculation(event.data).catch((error) => {
    openmmPromise?.then((module) => module._molarium_destroy()).catch(() => {});
    self.postMessage({
      type: 'error',
      id: event.data.id,
      message: error instanceof Error ? error.message : String(error),
    });
  });
});
