export const MOLARIUM_CONSTRAINT_DOCK_PROTOCOL = Object.freeze({
  schema: 'molarium.docking.protocol/v1',
  id: 'molarium-constraint-dock-1',
  version: '0.4.0',
  name: 'Molarium ConstraintDock-1',
  title: 'Reference-core and required H-bond constrained docking',
  status: 'experimental-browser-implementation',
  summary: 'Deterministic fixed-core ligand torsion search with explicit hydrogen-bond geometry and transparent rigid-receptor scoring.',
  lineage: Object.freeze([
    Object.freeze({
      role: 'published-method inspiration',
      method: 'Glide staged ligand docking',
      citation: 'Friesner RA et al. J Med Chem. 2004;47:1739-1749.',
      doi: '10.1021/jm0306430',
      url: 'https://pubmed.ncbi.nlm.nih.gov/15027865/',
      adopted: Object.freeze([
        'separate pose generation, torsional optimization, and final refinement stages',
        'reference-ligand core and receptor interaction constraints',
      ]),
      excluded: Object.freeze(['Glide grids', 'OPLS potential grids', 'GlideScore', 'commercial product defaults']),
    }),
    Object.freeze({
      role: 'published-method inspiration',
      method: 'ICM flexible docking in internal coordinates',
      citation: 'Totrov M, Abagyan R. Proteins. 1997;Suppl 1:215-220.',
      doi: '10.1002/(SICI)1097-0134(1997)1+<215::AID-PROT29>3.3.CO;2-I',
      url: 'https://pubmed.ncbi.nlm.nih.gov/9485515/',
      adopted: Object.freeze([
        'global internal-coordinate sampling interleaved with local minimization',
        'biased-probability Monte Carlo as published method lineage',
      ]),
      excluded: Object.freeze(['ICM receptor grids', 'ICM scoring function', 'Biased Probability Monte Carlo implementation']),
    }),
    Object.freeze({
      role: 'open-source method inspiration',
      method: 'Rowan openconf analogue pose generation',
      citation: 'Rowan Scientific. openconf: Modular conformer generation for docking and ensemble workflows. 2026.',
      url: 'https://github.com/rowansci/openconf',
      adopted: Object.freeze([
        'only sample free terminal rotors outside a constrained analogue core',
        'snap constrained atoms back to exact reference coordinates after search',
      ]),
      excluded: Object.freeze([
        'openconf source code', 'CrystalFF torsion library', 'MMFF94s minimizer',
        'ring flips', 'macrocycle moves', 'openconf clustering and selection',
      ]),
    }),
    Object.freeze({
      role: 'related congeneric-pose method considered, not reproduced',
      method: 'AutoPose R-group decomposition posing for RBFE',
      citation: 'Ponzoni L, York F, Kelley B. ChemRxiv. 2026.',
      doi: '10.26434/chemrxiv.15004703/v1',
      url: 'https://doi.org/10.26434/chemrxiv.15004703/v1',
      adopted: Object.freeze(['edit-lineage core identity serves the same congeneric-design use case']),
      excluded: Object.freeze(['RDKit R-group decomposition', 'Free-Wilson modeling', 'TMD RBFE workflow']),
    }),
    Object.freeze({
      role: 'constraint definition reference',
      method: 'Glide receptor and core constraints',
      citation: 'Schrodinger public Glide constraints documentation.',
      url: 'https://learn.schrodinger.com/public/python_api/2025-3/api/schrodinger.application.glide.constraints.html',
      adopted: Object.freeze(['complementary ligand donor/acceptor typing for receptor H-bond constraints']),
      excluded: Object.freeze(['Schrodinger source code and proprietary constraint scoring']),
    }),
    Object.freeze({
      role: 'restraint definition reference',
      method: 'ICM interaction restraints and ligand tethers',
      citation: 'MolSoft ICM public user documentation.',
      url: 'https://molsoft.com/~eugene/icmpro/ligand-tether.html',
      adopted: Object.freeze([
        'a distance restraint exists before the search and acts as a force potential outside its allowed range',
        'flat-bottom minimum/maximum distance restraints can be strongly weighted during redocking',
      ]),
      excluded: Object.freeze(['MolSoft source code and proprietary parameter values']),
    }),
    Object.freeze({
      role:'public product-behavior reference',
      method:'ICM small-molecule docking workflow',
      citation:'MolSoft ICM public small-molecule docking tutorial.',
      url:'https://molsoft.com/~jack/icmpro/start-dock.html',
      adopted:Object.freeze([
        'interaction restraints contribute a harmonic force during flexible-ligand optimization rather than acting only as a final filter',
      ]),
      excluded:Object.freeze([
        'ICM grid construction', 'ICM energy terms and weights',
        'ICM conformational-stack implementation', 'ICM commercial defaults',
      ]),
    }),
  ]),
  coreConstraint: Object.freeze({
    kind: 'reference-core-flat-bottom-rmsd',
    minimumHeavyAtoms: 3,
    toleranceAngstrom: 0.5,
    weightKcalMolPerAngstrom2: 25,
  }),
  hydrogenBondConstraint: Object.freeze({
    kind: 'explicit-D-H-A-flat-bottom',
    donorAcceptorDistanceAngstrom: Object.freeze([2.4, 3.5]),
    hydrogenAcceptorDistanceAngstrom: Object.freeze([1.2, 2.7]),
    minimumDhaAngleDegrees: 120,
    weightKcalMol: 15,
    requiredByDefault: true,
  }),
  sampling: Object.freeze({
    seed: 20260819,
    requestedConformers: 16,
    torsionMonteCarloSteps: 96,
    receptor: 'rigid',
    ligand: 'rigid-body and rotatable-bond degrees of freedom',
    stages: Object.freeze([
      'ETKDGv3 ligand conformers',
      'reference-core alignment and exact coordinate snap',
      'fixed-core receptor-aware torsion Monte Carlo',
      'explicit required H-bond search and audit',
      'transparent rigid-receptor cross-term scoring with relative OpenFF Sage ligand strain',
      'constraint audit and transparent reranking',
    ]),
  }),
  scoring: Object.freeze({
    identity: 'Molarium transparent physical score plus explicit restraint penalties',
    receptorSiteRadiusAngstrom: 8,
    relativeDielectric: 4,
    receptorInteractionReference: 'lowest rigid receptor cross energy among hard-snapped fixed-core starting seeds',
    ligandStrain: 'relative vacuum OpenFF Sage 2.1 intramolecular energy from the lowest fixed-core starting seed',
    interpretation: 'pose-ranking score; not a binding free energy',
    feasiblePosesRankFirst: true,
    notEquivalentTo: Object.freeze(['GlideScore', 'ICM Score']),
  }),
  implementation: Object.freeze({
    constraintGeometry: 'implemented',
    deterministicRanking: 'implemented',
    tamperEvidentLabbook: 'implemented',
    browserPoseGeneration: 'implemented-etkdgv3-plus-fixed-core-torsion-mc',
    browserLigandRefinement: 'implemented-rigid-receptor-fixed-core-torsion-mc',
    browserPocketRefinement: 'not-included-in-v0.3',
  }),
});

export const MOLARIUM_POSE_PROPAGATION_PROTOCOL = Object.freeze({
  ...structuredClone(MOLARIUM_CONSTRAINT_DOCK_PROTOCOL),
  id:'molarium-pose-propagation-1',
  version:'0.9.0',
  name:'Molarium Pose Propagation-1',
  title:'Edit-lineage reference-pose propagation and constrained refinement',
  summary:'Surviving reference heavy atoms remain exact except complete rings whose chemistry changed; those rings relax behind a fixed external boundary while H-bond restraints drive chemically gated pose generation.',
  novelty:Object.freeze({
    claim:'independent protocol composition; methodological novelty not established',
    establishedElements:Object.freeze([
      'reference/MCS placement for congeneric ligands',
      'constrained embedding and fixed-core analogue posing',
      'torsional Monte Carlo',
      'explicit hydrogen-bond restraints',
      'force-field relaxation',
    ]),
    molariumChanges:Object.freeze([
      'recorded graph-edit lineage replaces an inferred MCS when the analogue is edited in Molarium',
      'every surviving reference heavy atom is fixed except a complete transformed ring registered from the committed graph edit; its external scaffold boundary remains exact',
      'acyclic non-amide torsions and saturated-ring crankshafts containing no inherited atom are sampled; moves touching a perceived stereocenter, ring multiple bond, carbonyl, or lactam geometry are excluded',
      'a pharmacophore-capture stage precedes physical refinement, so ordinary physical energy cannot suppress generation toward the selected restraints; explicit strain/clash sanity gates reject chemically broken captures',
      'required contacts are lexicographic feasibility states, not energy terms that can be outweighed',
      'a deleted ligand contact participant can transfer to any donor/acceptor-role-compatible feature created at the same recorded edit boundary',
      'ligand-only relaxation is accepted only after a complete receptor-aware feasibility and score audit',
      'the complete protocol and run history are hash-linked in a browser-local labbook',
    ]),
  }),
  lineage:Object.freeze([
    Object.freeze({
      role:'RBFE pose-preparation practice',
      method:'MCS alignment with modified-substituent sampling',
      citation:'Cournia Z et al. J Chem Inf Model. 2017;57:2911-2937.',
      doi:'10.1021/acs.jcim.7b00564',
      url:'https://doi.org/10.1021/acs.jcim.7b00564',
      adopted:Object.freeze([
        'inherit a reference pose for a congeneric common region',
        'sample modified substituents and resolve clashes while maintaining the inherited pose',
      ]),
      excluded:Object.freeze(['binding free-energy estimation', 'unrestrained receptor equilibration']),
    }),
    Object.freeze({
      role:'FEP input-pose evidence',
      method:'Input Pose is Key to Performance of Free Energy Perturbation',
      citation:'Ohadi D et al. J Chem Inf Model. 2024;64:8859-8869.',
      doi:'10.1021/acs.jcim.4c01223',
      url:'https://pubmed.ncbi.nlm.nih.gov/39560439/',
      adopted:Object.freeze([
        'preserve ligand-based reference information',
        'treat explicit H-bond constraints as pose-generation evidence',
      ]),
      excluded:Object.freeze(['FEP+', 'study-specific water choices', 'reported affinity model']),
    }),
    Object.freeze({
      role:'template-pose baseline',
      method:'TEMPL constrained reference embedding',
      citation:'Pinheiro JP et al. J Chem Inf Model. 2025.',
      doi:'10.1021/acs.jcim.5c01985',
      url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12570141/',
      adopted:Object.freeze(['hard reference coordinates for the mapped common substructure']),
      excluded:Object.freeze(['TEMPL source code', 'reference-database search', 'shape-only ranking']),
    }),
    ...MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.lineage,
  ]),
  sampling:Object.freeze({
    ...structuredClone(MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.sampling),
    ligand:'recorded graph edits outside an exact surviving-heavy-atom scaffold',
    pharmacophoreCaptureSteps:96,
    exhaustiveCapturePolishSweeps:3,
    physicalRefinementSteps:96,
    stages:Object.freeze([
      'stable edit-lineage mapping of every surviving heavy atom',
      'post-sanitization role-compatible hypothesis generation for captured contacts affected by the graph edit',
      'exact reference-coordinate propagation',
      'exact restoration of surviving ligand-donor hydrogens used by required captured contacts',
      'restraint-biased torsion and saturated-ring internal-coordinate generation',
      'fixed-scaffold OpenFF Sage local relaxation',
      'explicit required H-bond audit',
      'constraint-feasible transparent ranking',
    ]),
  }),
  coordinateMapping:Object.freeze({
    identity:'stable designAtomId retained by recorded Molarium graph edits',
    referenceSet:'all ligand heavy atoms present when the reference pose is captured',
    inheritedRule:'same designAtomId and same element in reference and edited ligand',
    changedElementRule:'exclude from inherited set and leave movable',
    transformedRingRule:'when a committed edit changes an existing ring atom or existing ring bond, exclude the complete ring system, its directly multiply bonded exocyclic atoms, and attached hydrogens from the inherited set',
    transformedRingBoundaryRule:'surviving heavy atoms connected to the transformed ring only by an external single bond remain inherited and exact',
    transformedRingLedger:'every released atom ID, changed atom/bond, touched ring, fixed boundary, edit ID, and commit time is retained in source.posePropagationEditRegions',
    hydrogenRule:'hydrogens are never fixed by edit lineage',
    coordinateRule:'least-squares rigid alignment followed by exact reference-coordinate snap',
    minimumSurvivingHeavyAtoms:3,
    minimumMaximumTriangleDoubleAreaAngstrom2:1e-3,
    underdeterminedAction:'fail; never silently switch to global docking',
    atomIdentityRule:'designAtomId values are append-only within the molecule ledger; deleted IDs are never reassigned',
  }),
  contactFeatureMapping:Object.freeze({
    algorithm:'role-compatible-edit-boundary/v3',
    timing:'after successful chemical sanitization and local edit polish',
    receptorRule:'captured receptor participant identities and coordinates are immutable',
    ligandEligibility:'same donor/acceptor interaction role and the same recorded connected edit boundary; element, charge, aromaticity, neighbors, and feature type are provenance, not exclusion criteria',
    editBoundaryRule:'the removed and replacement features must connect to the same nonempty surviving designAtomId boundary through the cumulative connected edit region',
    bondOrderEditRule:'both surviving endpoints enter the edit region because bond order can create or destroy a pharmacophore without changing atom identity',
    scaffoldAnchorRule:'originating boundary IDs are immutable and excluded from the cumulative edit region',
    uniqueCandidateAction:'map automatically',
    ambiguousCandidateAction:'refine every candidate as an any-of restraint; optional user selection may narrow the set',
    zeroCandidateAction:'mark unavailable only when the connected replacement region contains no chemically perceived complementary donor or acceptor',
    geometryRule:'record as evidence; never use current coordinates to establish eligibility or break a tie',
    ligandDonorRule:'map donor and its explicit hydrogen as one tuple; a replacement hydrogen has no captured coordinate to restore',
    capturedFeatureRule:'display, capture, remap, availability, and run validation use the same typed molecular graph; untypable ligand contacts are not captured',
    subsequentEditRule:'a candidate set retains its originating boundary, cumulative live edit region, and candidate identities; later edits re-perceive interaction roles and recompute the boundary',
    historyRule:'undo and redo restore molecular graph, selected contacts, remaps, and unresolved proposals atomically',
    provenance:'record the complete remap chain, source and replacement atom IDs, exact signatures, boundary IDs, cumulative edit-region IDs, ordered edit IDs and topology hashes, candidate set, decision, and time',
  }),
  candidateInitialization:Object.freeze({
    countDefault:16,
    coordinateSource:'live edited-ligand coordinates plus deterministic captured-feature axis seeds; no ETKDG',
    featureGuidedSeeding:'for each selected contact with a captured ligand-feature reference point and a single-anchor noncore edit region, align the anchor-to-feature vector to the captured reference vector and enumerate axial rotations',
    featureGuidedAxialAnglesDegrees:Object.freeze([0, 60, -60, 120, -120, 180]),
    featureGuidedLimitation:'single-anchor noncore edit regions only; seeding changes no bond length, bond angle, or inherited coordinate',
    candidateFill:'deduplicate at 1e-6 Å and repeat the ordered unique seed list until the requested count is reached',
    independentVariable:'deterministic feature seed ordinal plus restraint-biased internal-coordinate chain seed',
    baseSeed:20260819,
    candidateSeedXorMultiplierUint32:2654435769,
    candidateSeedFormula:'uint32(baseSeed XOR imul(candidateOrdinalOneBased, 0x9e3779b9))',
    prng:'mulberry32 uint32 implementation in stormm/core.mjs',
    ligandDonorHydrogenRestoration:'for each required ligand-donor contact, restore the surviving explicit H to its captured reference coordinate before restraint-biased generation',
    duplicateHydrogenRule:'first selected contact in captured order restores a ligand hydrogen; later contacts using that hydrogen are audited and skipped',
  }),
  torsionMonteCarlo:Object.freeze({
    method:'molarium-fixed-core-torsion-mc/v1',
    stepsDefault:96,
    temperatureStartKelvin:900,
    temperatureEndKelvin:150,
    temperatureSchedule:'geometric over step/(steps-1)',
    proposalAnglesDegrees:Object.freeze([-180, -120, -90, -60, -30, -15, 15, 30, 60, 90, 120, 180]),
    rotorSelection:'uniform over eligible rotors',
    angleSelection:'uniform over the discrete proposal-angle list',
    eligibleBond:'acyclic, non-aromatic, non-amide-like single bond between non-hydrogen atoms',
    movingSide:'the graph component containing no inherited atom; terminal one-atom components are excluded',
    metropolisBoltzmannKcalMolKelvin:0.00198720425864083,
    feasibilityTransitions:'infeasible-to-feasible always accepted; feasible-to-infeasible always rejected',
    equalFeasibilityAcceptance:'accept downhill; otherwise accept with exp(-deltaE/(kB*T))',
    bestPoseOrder:'feasible before infeasible, then lower objective',
  }),
  restraintBiasedGeneration:Object.freeze({
    method:'molarium-restraint-biased-internal-coordinate-search/v3',
    captureStepsDefault:96,
    capturePolishSweeps:3,
    physicalRefinementStepsDefault:96,
    temperatureStartKelvin:900,
    temperatureEndKelvin:150,
    temperatureSchedule:'geometric over step/(steps-1)',
    torsionAnglesDegrees:Object.freeze([-180, -120, -90, -60, -30, -15, 15, 30, 60, 90, 120, 180]),
    ringCrankshaftAnglesDegrees:Object.freeze([-60, -45, -30, -20, -15, 15, 20, 30, 45, 60]),
    localLineFractions:Object.freeze([0.5, 0.75, 1, 1.25]),
    moveSelection:'uniform over eligible acyclic torsions and saturated-ring crankshafts',
    ringEligibility:'isolated non-aromatic 4-12 membered rings with a movable arc containing no inherited atom; rings sharing any atom with another perceived ring are excluded; moves touching perceived tetrahedral stereocenters, ring multiple-bond atoms, or lactam/conjugated ring geometry are excluded',
    ringMove:'rotate one safe ring arc and its attached substituents about two fixed arc endpoints; ring closure and every bond length are preserved; this is not a general ring-conformer generator',
    localLineSearch:'evaluate four deterministic fractions of each proposed internal-coordinate angle and retain the lowest current-stage objective',
    capturePolish:'after stochastic capture proposals, perform up to three deterministic best-improvement sweeps over every eligible move, angle, and line fraction',
    captureObjective:'sum of selected required-contact flat-bottom penalties plus penalties only for exceeding the registered ligand-strain and steric-clash sanity gates; ordinary physical energy cannot outweigh pharmacophore capture',
    captureMaximumRelativeLigandStrainKcalMol:100,
    captureMaximumAdditionalStericClashes:2,
    captureMaximumAdditionalLennardJonesKcalMol:100,
    captureSanityReference:'lowest-strain exact-core starting seed; steric-clash count and Lennard-Jones repulsion are measured from their least severe exact-core starting seeds',
    stageTransition:'physical refinement starts only when every selected required contact is geometrically satisfied and the chemical-sanity gate passes',
    physicalRefinementObjective:'rigid-receptor cross energy + relative Sage ligand strain + core and flat-bottom H-bond penalties',
    acceptance:'annealed stochastic line-search heuristic on the current-stage objective; entering feasibility is always accepted and leaving feasibility is rejected; not equilibrium Metropolis/Hastings or ICM BPMC',
    captureFailure:'return the closest audited pharmacophore geometry as infeasible; do not run physical relaxation that could hide the miss',
    finalAudit:'ordinary unamplified objective and hard required-contact feasibility',
    relationToIcm:'independent implementation of the publicly documented restraint-during-search principle; not ICM BPMC, receptor grids, score, source code, or proprietary defaults',
  }),
  fixedScaffoldRelaxation:Object.freeze({
    engine:'OpenMM 8.2 Reference platform compiled to WebAssembly',
    forcefield:'OpenFF Sage 2.1.0 valence and vdW parameters',
    chargeModel:'RDKit Gasteiger charges, 12 iterations',
    forcefieldSourceSha256:'694df155d76d06baf7f4c9603e092798f11b6c758e08bbd86571de03350178ea',
    environment:'vacuum',
    constraintMode:'none',
    iterationsDefault:60,
    stepScale:1e-4,
    maximumDisplacementAngstromPerIteration:0.01,
    fixedAtoms:'all inherited heavy atoms restored bit-for-bit after every iteration',
    movableAtoms:'hydrogens and non-inherited atoms',
    receptorIncludedInRelaxation:false,
    acceptance:'accept if feasibility improves, or if feasibility is unchanged and the complete objective strictly decreases',
  }),
  scoring:Object.freeze({
    ...structuredClone(MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.scoring),
    receptorSiteRadiusAngstrom:8,
    pairCutoffAngstrom:8,
    receptorIntegrityToleranceAngstrom:1e-6,
    relativeDielectric:4,
    coulombConstantKcalAngstromPerMolE2:332.063713299,
    sigmaCombiningRule:'arithmetic mean (Lorentz)',
    epsilonCombiningRule:'geometric mean (Berthelot)',
    maximumPairRepulsionKcalMol:1e6,
    stericClashDiagnostic:'distance < 0.72 * combined sigma; diagnostic only',
    ligandStrainWeight:1,
    totalObjective:'cross Lennard-Jones + cross Coulomb + relative ligand strain + core penalty + H-bond penalties',
    finalOrder:'feasible first; total objective ascending; original candidate index ascending',
  }),
  requiredContactGeometry:Object.freeze({
    captureCriteria:Object.freeze({
      donor:'N, O, or S with an explicit bonded hydrogen',
      acceptor:'nonpositive O/S/F, or nonpositive N with degree below 4 and no bonded hydrogen',
      hydrogenAcceptorDistanceAngstrom:Object.freeze([1.2, 2.6]),
      minimumDhaAngleDegrees:135,
      scope:'all cross receptor-ligand contacts sorted by H-A distance; viewer display limits do not constrain capture',
    }),
    donorAcceptorDistanceAngstrom:Object.freeze([2.4, 3.5]),
    hydrogenAcceptorDistanceAngstrom:Object.freeze([1.2, 2.7]),
    minimumDhaAngleDegrees:120,
    flatBottomWeightKcalMol:15,
    angleNormalizationDegrees:30,
    deletedLigandParticipant:'apply role-compatible-edit-boundary/v3 after sanitization; evaluate multiple candidates as an any-of restraint; otherwise omit with ligand-feature-unavailable audit record',
  }),
  exclusions:Object.freeze([
    'automatic MCS for independently imported analogues',
    'tautomer, protomer, stereoisomer, or symmetry enumeration',
    'macrocycle-specific, fused-ring concerted, or bond-angle/bond-length moves beyond saturated-ring crankshafts',
    'receptor or crystallographic-water relaxation',
    'desolvation, entropy, affinity, or binding-free-energy estimation',
    'replacement of a deleted reference contact without complementary donor/acceptor perception and edit-boundary evidence',
  ]),
  implementation:Object.freeze({
    ...structuredClone(MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.implementation),
    browserPoseGeneration:'implemented-recorded-edit-lineage-plus-restraint-biased-torsion-and-ring-generation',
    browserLigandRefinement:'implemented-restraint-biased-internal-coordinate-search-plus-fixed-scaffold-sage-relaxation',
  }),
});

export function protocolSnapshot(overrides = {}) {
  return {
    ...structuredClone(MOLARIUM_CONSTRAINT_DOCK_PROTOCOL),
    coreConstraint: {
      ...MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.coreConstraint,
      ...(overrides.coreConstraint || {}),
    },
    hydrogenBondConstraint: {
      ...MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.hydrogenBondConstraint,
      ...(overrides.hydrogenBondConstraint || {}),
    },
    sampling: {
      ...MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.sampling,
      ...(overrides.sampling || {}),
      stages: [...(overrides.sampling?.stages || MOLARIUM_CONSTRAINT_DOCK_PROTOCOL.sampling.stages)],
    },
  };
}

export function posePropagationProtocolSnapshot(overrides = {}) {
  const base = MOLARIUM_POSE_PROPAGATION_PROTOCOL;
  return {
    ...structuredClone(base),
    coreConstraint:{ ...base.coreConstraint, ...(overrides.coreConstraint || {}) },
    hydrogenBondConstraint:{
      ...base.hydrogenBondConstraint, ...(overrides.hydrogenBondConstraint || {}),
    },
    restraintBiasedGeneration:{
      ...base.restraintBiasedGeneration, ...(overrides.restraintBiasedGeneration || {}),
    },
    sampling:{
      ...base.sampling, ...(overrides.sampling || {}),
      stages:[...(overrides.sampling?.stages || base.sampling.stages)],
    },
  };
}
